name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run Tests
      run: |
        cd frontend
        npm test
        
    - name: Build
      run: |
        cd frontend
        npm run build
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == "refs/heads/main"
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build
      run: |
        cd frontend
        npm run build
        
    - name: Deploy to Production
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        # Add deployment steps here
        # This could be deploying to a cloud service like Vercel, Netlify, or AWS
        echo "Deployment steps would go here"
